### ISSUE TITLE
when I open the activity stream for a user it does not fully open.

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/PAM#1]
clicking user activity feed it does not fully open, just a small white pane at top of screen:
![2021-12-15_13-11](https://user-images.githubusercontent.com/106644/146265658-15de1add-ca3f-4c94-aa46-fdb808dc175e.png)

Individual task activity also blank white page.

Will see if I can provide more info first thing when I wake up, headed to bed now, good night.

**Comment by Chaosmeister** [comment]
hmm  I made a few mistakes while cleaning up but generally it works on my side.  
we'll figure it out :v:

**Comment by Chaosmeister** [comment]
ahh I got it already

I shouldn't develop on a windows machine and deploy to linux machines 😅

**Comment by Chaosmeister** [comment]
I fixed the repo and the release,  works on my production instance now

**Comment by Jieiku** [comment]
Working perfect here. I think I may have had the permissions incorrect when I first installed it. I did a git clone and moved the plugin into the plugins directory but forgot to set ownership of the files.

I apologize and thanks again, This is working great!!
